export const Course = [
  {
    id: 1,
    title: "LEGO",
    ageGroup: "Ages 5-8",
    color: "from-red-400 to-orange-400",
    icon: "🧱",
    description: "Build and create with colorful LEGO bricks",
    features: ["Basic Building", "Creativity", "Problem Solving"],
  },
  {
    id: 2,
    title: "DUPLO",
    ageGroup: "Ages 3-5",
    color: "from-pink-400 to-rose-400",
    icon: "🎀",
    description: "Large blocks designed for little hands",
    features: ["Motor Skills", "Imagination", "Fun Learning"],
  },
  {
    id: 3,
    title: "GAME DEVELOPMENT",
    ageGroup: "Ages 9-14",
    color: "from-purple-400 to-indigo-400",
    icon: "🎮",
    description: "Create your own interactive games",
    features: ["Coding Basics", "Game Logic", "Creative Thinking"],
  },
  {
    id: 4,
    title: "3D DESIGNING",
    ageGroup: "Ages 10-15",
    color: "from-cyan-400 to-blue-400",
    icon: "🎨",
    description: "Design and model in 3D space",
    features: ["3D Modeling", "Spatial Awareness", "Design Thinking"],
  },
  {
    id: 5,
    title: "ELECTRONICS",
    ageGroup: "Ages 11-16",
    color: "from-green-400 to-emerald-400",
    icon: "⚡",
    description: "Learn circuits and electronics",
    features: ["Circuit Design", "Experimentation", "STEM Skills"],
  },
  {
    id: 6,
    title: "PYTHON",
    ageGroup: "Ages 12-17",
    color: "from-yellow-400 to-amber-400",
    icon: "🐍",
    description: "Master Python programming language",
    features: ["Programming", "Logic", "Advanced Coding"],
  },
];
