export const Course = [
  {
    id: 1,
    title: "Little Geniuses ",
    ageGroup: "Ages4-5",
    color: "from-red-400 to-orange-400",
    icon: "🧮",
    fullDescription: " LEGO Duplo, STEM Park, Coding Express, MatataBot Learn basics through play & storytelling ",
    features: [" Creativity", "problem-solving", "early STEM skills through play"],
  },
  {
    id: 2,
    title: "Young Innovators ",
    ageGroup: "Ages 5-8",
    color: "from-blue-400 to-gray-400",
    icon: "🤖",
    fullDescription: "Large blocks designed for little handsWeDo 2.0: Build, code, and automate with LEGO models ",
    features: ["Motor Skills", "Imagination", "Fun Learning"],
  },
  {
    id: 3,
    title: "Rising Stars ",
    ageGroup: "Ages 8-11",
    color: "from-yellow-400 to-orange-400",
    icon: "⭐",
    fullDescription: " Spike Prime: Robotics, coding, and AI.  Mindstorm EV3: Advanced robotics and programming.  ",
    features: ["Coding Basics", "Game Logic", "Creative Thinking"],
  },
  {
    id: 4,
    title: "Future Leaders  ",
    ageGroup: "Ages 11-16",
    color: "from-green-600 to-blue-200",
    icon: "👑",
    fullDescription: " Spike Prime (advanced): Robotics, coding, and AI.  Mindstorm EV3: Advanced robotics and programming.  ",
    features: ["Coding Basics", "Game Logic", "Creative Thinking"],
  },
  {
    id: 5,
    title: "Game Development",
    ageGroup: "Ages 9-14",
    color: "from-gray-400 to-purple-400",
    icon: "🎮",
    fullDescription: "Students learn core programming concepts, game mechanics, animation, and creative storytelling using beginner-friendly development tools.",
    features: ["Coding Basics", "Game Logic", "Creative Thinking"],
  },
  {
    id: 6,
    title: "3D DESIGNING",
    ageGroup: "Ages 10-15",
    color: "from-teal-400 to-blue-400",
    icon: "🎨",
    fullDescription: "Explore creativity through designing and modeling exciting 3D objects, characters, and environments.",
    features: ["3D Modeling", "Spatial Awareness", "Design Thinking"],
  },
  {
    id: 7,
    title: "ELECTRONICS",
    ageGroup: "Ages 11-16",
    color: "from-yellow-400 to-amber-200",
    icon: "⚡",
    fullDescription: "Learn how electronic components work together while building creative projects using LEDs, buzzers, motors, and  microcontrollers.",
    features: ["Circuit Design", "Experimentation", "STEM Skills"],
  },
  {
    id: 8,
    title: "PYTHON",
    ageGroup: "Ages 12-17",
    color: "from-green-300 to-emerald-500",
    icon: "🐍",
    fullDescription: "The Coding course introduces kids to the fundamentals of programming, helping them understand how software and digital applications are built.",
    features: ["Programming", "Logic", "Advanced Coding"],
  },
];
